#If its a bash shell and .bashrc exists then source it.
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
    fi
fi


#Enable bash-completion.

if [ -f /usr/local/bin/brew ]; then
	if [ -f $(/usr/local/bin/brew --prefix)/etc/bash_completion ]; then
		. $(/usr/local/bin/brew --prefix)/etc/bash_completion
	fi
fi

