#Create some aliases to print today's and yesterday's date in "serial number" format.
alias Today="date '+%Y-%m-%d'"
alias Yesterday="date '+%Y-%m-%d' --date=yesterday"

#force bc to use the standard math library.
#This makes bc perform decimial calculations by default.
alias bc="bc -l"

#update my debian/ubuntu systems
alias system-update="sudo apt-get update; sudo apt-get dist-upgrade"
