#Create some aliases to print today's and yesterday's date in "serial number" format.
alias Today="date '+%Y-%m-%d'"
alias Yesterday="date '+%Y-%m-%d' --date=yesterday"

#force bc to use the standard math library.
#This makes bc perform decimial calculations by default.
alias bc="bc -l"

#update my debian/ubuntu systems
alias system-update="sudo apt update; sudo apt full-upgrade && sudo apt autoremove"


#OSX specific aliases
if [ "$OPERATING_SYSTEM" == "Darwin" ]; then
	alias ls="ls -G"
	alias vi="vim"
	alias date="gdate"
fi

alias vagrant-ansible-playbook="ansible-playbook --private-key=.vagrant/machines/default/virtualbox/private_key -u vagrant -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory --diff"

